var header = new Headroom(document.getElementById("header"), { tolerance: 0, offset : 70, classes: { initial: "animated", pinned: "slideDown", unpinned: "slideUp" } }); header.init(); var chakhsu = function(r){function t(){return b[Math.floor(Math.random()*b.length)]}function e(){return String.fromCharCode(94*Math.random()+33)}function n(r){for(var n=document.createDocumentFragment(),i=0;r>i;i++){var l=document.createElement("span");l.textContent=e(),l.style.color=t(),n.appendChild(l)}return n}function i(){var t=o[c.skillI];c.step?c.step--:(c.step=g,c.prefixP<l.length?(c.prefixP>=0&&(c.text+=l[c.prefixP]),c.prefixP++):"forward"===c.direction?c.skillP<t.length?(c.text+=t[c.skillP],c.skillP++):c.delay?c.delay--:(c.direction="backward",c.delay=a):c.skillP>0?(c.text=c.text.slice(0,-1),c.skillP--):(c.skillI=(c.skillI+1)%o.length,c.direction="forward")),r.textContent=c.text,r.appendChild(n(c.prefixP<l.length?Math.min(s,s+c.prefixP):Math.min(s,t.length-c.skillP))),setTimeout(i,d)}var l="活着，就是",o=["为了折腾","为了生活","为了爱情","为了家庭","为了自己","为了将来"].map(function(r){return r+"."}),a=2,g=1,s=5,d=75,b=["rgb(110,64,170)","rgb(150,61,179)","rgb(191,60,175)","rgb(228,65,157)","rgb(254,75,131)","rgb(255,94,99)","rgb(255,120,71)","rgb(251,150,51)","rgb(226,183,47)","rgb(198,214,60)","rgb(175,240,91)","rgb(127,246,88)","rgb(82,246,103)","rgb(48,239,130)","rgb(29,223,163)","rgb(26,199,194)","rgb(35,171,216)","rgb(54,140,225)","rgb(76,110,219)","rgb(96,84,200)"],c={text:"",prefixP:-s,skillI:0,skillP:0,direction:"forward",delay:a,step:g};i()};chakhsu(document.getElementById('chakhsu')); if ('addEventListener' in document) { document.addEventListener('DOMContentLoaded', function() { FastClick.attach(document.body); }, false);};

function switchNightMode(){var night=document.cookie.replace(/(?:(?:^|.*;\s*)night\s*\=\s*([^;]*).*$)|^.*$/,"$1")||"0";if(night=="0"){document.body.classList.add("night");document.cookie="night=1;path=/";console.log("夜间模式开启");Dialog.init('已手动开启网站暗黑模式！',1000);}else{document.body.classList.remove("night");document.cookie="night=0;path=/";console.log("夜间模式关闭");Dialog.init('已手动关闭网站暗黑模式！',1000);}}(function(){if(document.cookie.replace(/(?:(?:^|.*;\s*)night\s*\=\s*([^;]*).*$)|^.*$/,"$1")===""){if(new Date().getHours()>23||new Date().getHours()<6){document.body.classList.add("night");document.cookie="night=1;path=/";console.log("夜间模式开启");Dialog.init('天黑了，已自动开启网站暗黑模式！',2000);}else{document.body.classList.remove("night");document.cookie="night=0;path=/";console.log("夜间模式关闭")}}else{var night=document.cookie.replace(/(?:(?:^|.*;\s*)night\s*\=\s*([^;]*).*$)|^.*$/,"$1")||"0";if(night=="0"){document.body.classList.remove("night")}else{if(night=="1"){document.body.classList.add("night")}}}})();

function showhidediv(id){var sbtitle=document.getElementById(id);if(sbtitle){if(sbtitle.style.display=="block"){sbtitle.style.display="none"}else{sbtitle.style.display="block"}}};

pangu.spacingElementById('post-content');pangu.spacingElementByClassName('post-header-thumb-title');pangu.spacingElementByClassName('meta-comments');pangu.spacingElementByClassName('comment-content');

function checkboxOnclick(checkbox){if(checkbox.checked==true){Dialog.init('开启私密评论后，提交的评论仅文章作者和评论人可见！',1800);document.getElementById('textarea').style.backgroundImage="url(https://cdn.jsdelivr.net/gh/caiweill/cdn/pinghsu/images/simi.png)";}else{document.getElementById('textarea').style.backgroundImage="none";}};

document.body.oncopy = function() {Dialog.init('<i class="fa fa-files-o" aria-hidden="true"></i> 您已复制成功，若要转载请务必保留原文链接！尊重他人劳动成果，谢谢！',2000);};
